1016 upload to worker
UKGovernmentBEIS/beis-opss-cosmetics pull request #1923
Opened 2021-01-12 10:02 UTC by slawosz

Direct upload for zip files. Uses JS `ActiveStorage` library to send files directly to S3.

2021-01-12 15:48 UTC, nasirkhanbeis commented
Few issues spotted:
1. when I upload eg. 100 files, checking files counter still show as 1 - Expected to show correct count 100 files
2. when I upload 100 files, page becomes very slow like frozen. - Need show some spinner or disable the continue button 
![image](https://user-images.githubusercontent.com/47983567/104337604-96dd4d00-54ed-11eb-93de-86346721f2bb.png)

2021-01-12 16:20 UTC, slorek requested changes

2021-01-12 16:20 UTC, slorek commented on cosmetics-web/app/services/direct_upload_handler.rb
> +    end
Please change: there [was a change](https://github.com/UKGovernmentBEIS/beis-opss-cosmetics/pull/1909) to the way this was scheduled to prevent race conditions. This is now automatically scheduled by the `MasterAnalyzer` when you call `attach` (see https://github.com/UKGovernmentBEIS/beis-opss-cosmetics/blob/master/cosmetics-web/app/analyzers/master_analyzer.rb#L24). Please remove this because it will result in the job running twice and causing either a race condition or an error.

2021-01-12 16:20 UTC, slorek commented on cosmetics-web/app/services/direct_upload_handler.rb
> +      notification_file.uploaded_file.attach(uploaded_file)
Suggestion: Delaying the `NotificationFile` record creation could result in the user seeing no uploaded files until the job was run. In normal conditions I suppose this shouldn't happen, but if there was a delay in the job running it could be confusing.

I think this `attach` call is the expensive one. To avoid the problem we could instead create the `NotificationFile` record immediately [here in the controller](https://github.com/UKGovernmentBEIS/beis-opss-cosmetics/pull/1923/files#diff-e036390f6129d43999b8fa84fcf4a382a627cd0fffd1ab72b3956d4b185449bdR18) and then schedule the attachment of the file as the asynchronous job.

2021-01-12 17:28 UTC, slawosz commented on cosmetics-web/app/services/direct_upload_handler.rb
> +      notification_file.uploaded_file.attach(uploaded_file)
Attach is not particulary expensive, its the loop which makes it expensive.

2021-01-12 17:29 UTC, slawosz commented on cosmetics-web/app/services/direct_upload_handler.rb
> +      notification_file.uploaded_file.attach(uploaded_file)
User does not see notification files as such, so I don't think its an issue.

2021-01-14 10:49 UTC, nasirkhanbeis approved these changes
Tested this on review app, looking good as expected, 
Verified this new approach with 100 files upload at a time, feedbacks user appropriately if there's any error with any files however processes remainder files as expected. 
Also verified all other possible zip file upload scenarios such as duplicate file, non zip file, zip file with no product xmls, zip file with virus file . all returns back with expected errors. 
happy to approve this.

2021-01-14 11:11 UTC, scruti commented on cosmetics-web/app/jobs/direct_upload_handler_job.rb
> +end
Since the job is not being called... could we remove it?

2021-01-14 11:12 UTC, slawosz commented on cosmetics-web/app/jobs/direct_upload_handler_job.rb
> +end
I would keep it. If we will have some issues its just a matter of `git reverse` to start using it.

2021-01-14 11:14 UTC, slorek requested changes
I don’t think you need to schedule `NotificationFileProcessorJob` manually. The `MasterAnalyzer` will do it.

Also I think we should add test coverage on the controller.

2021-01-14 11:14 UTC, slorek commented on cosmetics-web/app/controllers/responsible_persons/notification_files_controller.rb
> +      NotificationFileProcessorJob.perform_later(notification_file.id)
See previous comment. I think the `MasterAnalyzer` will schedule this job automatically, so this will result in it being run twice.

2021-01-14 11:14 UTC, slorek commented on cosmetics-web/app/jobs/direct_upload_handler_job.rb
> +end
✂️

2021-01-14 11:20 UTC, slawosz commented on cosmetics-web/app/jobs/direct_upload_handler_job.rb
> +end
As I mentioned, I left this as possibility when processing in request would take too much time.

2021-01-14 11:25 UTC, scruti approved these changes
![image](https://user-images.githubusercontent.com/1227578/104584817-10df1480-565b-11eb-9f98-d5c2423acd5f.png)

Suggested to remove the uncalled job class.

2021-01-14 11:34 UTC, scruti commented on cosmetics-web/app/jobs/direct_upload_handler_job.rb
> +end
Can we actually revert a squashed commit? (we squash on merge)
Even in that case... wouldn't a `git revert` re-introduce the class again if there is a commit removing it?

2021-01-15 10:32 UTC, scruti commented on cosmetics-web/spec/requests/responsible_persons/notification_files_spec.rb
> +        post "/responsible_persons/#{responsible_person.id}/notification_files", params: params
Suggestion:
About this:
```
RSpec/MessageSpies:
  Exclude:
    - spec/requests/responsible_persons/notification_files_spec.rb 
 ```
 This is the `to_receive` vs `have_received` rule on the spies right?
 Wouldn't this work without having to bypass the rule?
 
```suggestion
        handler = double
        allow(DirectUploadHandler).to receive(:new).with(file_ids, file_names, responsible_person.id, submit_user.id) { handler }
   
        post "/responsible_persons/#{responsible_person.id}/notification_files", params: params
        
        expect(handler).to have_received(:call)
```

2021-01-15 10:33 UTC, scruti commented on cosmetics-web/.rubocop.yml
> +
```suggestion
```

2021-01-15 10:49 UTC, slorek approved these changes

2021-01-15 10:50 UTC, scruti commented on cosmetics-web/spec/requests/responsible_persons/notification_files_spec.rb
> +
So sorry about this :/
```suggestion

```

2021-01-15 10:51 UTC, scruti commented on cosmetics-web/spec/requests/responsible_persons/notification_files_spec.rb
> +
So sorry about this :/
```suggestion

```

2021-01-15 11:45 UTC, merged