CSV download
UKGovernmentBEIS/beis-opss-cosmetics pull request #2017
Opened 2021-03-05 09:52 UTC by slawosz

Basic implementation on CSV download. Might be slow for RP's which lot of notifications, but this is something we can easily monitor on the logs.

2021-03-05 11:12 UTC, slorek requested changes

2021-03-05 11:12 UTC, slorek commented on cosmetics-web/app/decorators/notification_decorator.rb
> +  end
Please change: this will break if any of the values contain a `"` or `,` character. I would recommend using the CSV standard library, see https://github.com/UKGovernmentBEIS/beis-opss-psd/blob/master/app/decorators/businesses_decorator.rb#L4-L9 for an example we used in PSD, as this will handle all of the escaping automatically.

2021-03-05 11:50 UTC, scruti commented on cosmetics-web/app/decorators/notifications_decorator.rb
> +                :cpnp_notification_date]
:question: Shouldn't this constant be declared within `NotificationDecorator`?

2021-03-05 11:56 UTC, slawosz commented on cosmetics-web/app/decorators/notifications_decorator.rb
> +                :cpnp_notification_date]
I prefer to have `ATTRIBUTES` in here, as it also has headers here and this is parent class.

2021-03-05 12:37 UTC, scruti approved these changes

2021-03-05 15:22 UTC, nasirkhanbeis commented
Spotted few issues
1. Link to read as "Download a CSV of notified products"
2. time stamp to be in GMT format - not in UTC
3. Level 1, level2 and level 3 missing - agreed to fix this separately

2021-03-08 10:28 UTC, slorek approved these changes

2021-03-08 12:54 UTC, nasirkhanbeis approved these changes
looking good as expected. Re: category and subcategory, we agreed to implement this separately.

2021-03-08 15:49 UTC, merged