Rails 6.1
UKGovernmentBEIS/beis-opss-cosmetics pull request #2088
Opened 2021-04-23 09:45 UTC by slawosz

App updated to rails 6.1

2021-04-28 11:04 UTC, scruti commented on cosmetics-web/app/controllers/submit_application_controller.rb
> +  helper_method :root_path
:question: 
Do we need this override when `application_controller` has this?:
```ruby
  def root_path
    submit_domain? ? submit_root_path : search_root_path
  end
  ```

2021-04-28 11:31 UTC, scruti commented on cosmetics-web/app/controllers/responsible_persons/formulation_upload_controller.rb
> +        @component.formulation_file.delete
Question :question: 
I am confused about this change. ActiveStorage guides does not have reference to `#delete` anywhere ( https://edgeguides.rubyonrails.org/active_storage_overview.html#removing-files ). But seems you tested this and it actually purges the blob according to the specs... is `delete` an alias? Does something different than `purge`? :man_shrugging:

2021-04-28 11:36 UTC, scruti commented on cosmetics-web/app/helpers/component_build_helper.rb
> +      component.errors.reject { |_error| attribute.to_s.include? "cmrs." }.map { |error| { text: error.message, href: "#component_cmrs_attributes_0_name" } }
:raising_hand_man:  
Not 100% sure on this but better safe than sorry. From what I see in the changes now the interface is `error#attribute`  (as used in line 3). I belive the line 4 could be wrong then:
```suggestion
      component.errors.reject { |error| error.attribute.to_s.include? "cmrs." }.map { |error| { text: error.message, href: "#component_cmrs_attributes_0_name" } }
```

2021-04-28 11:39 UTC, scruti commented on cosmetics-web/app/helpers/nanomaterial_helper.rb
> +    NanoElement.purposes.index_with { |purpose| get_label_for_nanomaterial_purpose(purpose) }
Nice <3

2021-04-28 15:00 UTC, slawosz commented on cosmetics-web/app/helpers/component_build_helper.rb
> +      component.errors.reject { |_error| attribute.to_s.include? "cmrs." }.map { |error| { text: error.message, href: "#component_cmrs_attributes_0_name" } }
Good catch!

2021-04-29 09:25 UTC, scruti commented on cosmetics-web/spec/requests/secondary_authentication/sms_spec.rb
> +        # )
Just highlighting this for attention. Was this temporal?

2021-05-04 13:20 UTC, scruti approved these changes
LGTM!

2021-05-04 14:53 UTC, scruti commented
@slawosz there is an error (triggered by Nasir testing on review app) due to a missing gem: 
https://sentry.io/organizations/beis/issues/2380248575/?project=1398436

2021-05-04 14:53 UTC, nasirkhanbeis approved these changes
Tested this on review app 2088, looking good as expected. 
Verified all journeys, manual and zip upload, validated file uploads, validation errors, create user, invite user etc. all good!

2021-05-04 14:54 UTC, scruti requested changes
Please change: Noticed an exception due to a missing gem for image processing.
https://sentry.io/organizations/beis/issues/2380248575/?project=1398436

2021-05-04 18:10 UTC, scruti approved these changes

2021-05-06 19:24 UTC, merged