New flow for adding notifications
UKGovernmentBEIS/beis-opss-cosmetics pull request #2277
Opened 2021-10-12 10:47 UTC by slawosz

https://cosmetics-pr-2277-submit-web.london.cloudapps.digital/

# New, simplified notification flow

Instead of having one, complicated flow with many redirections, this introduces task based notification flow.
To create a notification, the user have to finish several tasks:

1. Define a product
2. Define a nanomaterials
3. Define how multiple items are used (only for multi item products)
4. Define items
5. Submit

Each task is available from main, `draft` page. Unlike in old flow, it is possible to revisit and edit already completed task. 
It is also possible to add/remove nanomaterials and items.

# Why?

## Technical why

The code of the wizard was quite complicated - the biggest problems were *hard to follow* redirections which were causing a lot of troubles. There was some legacy code, no longer used - this work gave good opportunity to review it and get rid of it.

## UI why

The new task based flow gives user several benefits:
* predictable behaviour
* possibility of editing notification at any stage
* possibility of stopping adding notification without loosing progres

# Tasks
## Add product

Adding basic product informations: name, if contains nanomaterials or multiple items.

## Add nanomaterials

This task is available only if product notification has nanomaterial. In the task, the user needs to define nanomaterial name and confirms that nanomaterial conforms to regulations.

## Define multi-item kit

This task is available only if product notification has more than one item. It is used to gather information of PH in case when elements are mixed.

## Define items

The 'main' task. Gathers all infrmation of the product. Collects information about nanomaterials (if present), harmful ingredients and item photo and formulation

# Technical documentation

## State machine migration

This work introduces new states. `component_complete` is semi-new state - in old wizard, it was one of the intermediate state without any function. Now, it indicates that notification can be submited.
The mapping between old and new states is as following:

```
draft_complete => product_name_added
```

This transition occurs when `draft_complete` notification has missing some information. The user has to go through all of the steps again. `product name_added` is being listed so user can revisit such notification.

```
draft_complete => components_complete
```

This transition occurs when `draft_complete` notification has all information. The user can submit the notification right away.

```
product_name_added => empty
```

When notification had `product_name_added` state, only name was added. There is no point to keep such notification in the system. `empty` is state for new notification, however we don't list this state, so in practice it 'hiddes' notification. In the future we should remove all empty notifications.

 ```
import_country_added => empty
```
The `import_country_added_state` is old, long unused state. 

```
notification_file_imported => empty
```

This is old zip file state. We never listed this state so it is set to empty.

```
components_complete => empty
```

This state is when one of components is completed. We never listed this state so it is set to empty. Please note, that `components_complete` state has new role - now it indicates ready to submit notification.

```
draft_complete => components_complete
```
This is transition where notification can be notified right away.

# Database changes

## New, one to one nanomaterial - nanoelement relation

Previously, the `NanoMaterial` model acted as container for `NanoElement`. However, the `NanoElement` model is the one that contains all information about nanomaterial, and since the new flow declares nanoelements first, it was required to change this model. This comes from the fact that `NanoMaterial` is added to component. In the future, it is possible to unify all `NanoMaterial` and `NanoElement` records, as I have chosen not to do as part of this work.

## New, many to many component - nanomaterial relation
In new flow, same nanomaterial can be added to several items, hence the need of `many to many` relation.

Component has new fields that were previously in nanomaterial
* `exposure_routes` moved to components
* `exposure_conditions` moved to components
## New, one to many notification - component relation

As the nanomaterial is added before item, it need to be related to notification.

## Other changes
* `previous_state` column in `notifications` to store previous state when state is being changed to lower
* `routing_questions_answers` to store anwsers to routing questions - questions that help to redirect to next steps, so those will be preselected next time user is going over particular step.

## Wicked Wizard

### Introduction of new methods

Cosmetics is using wicked wizard. To make it much more friendly and usable, some methods are renamed and new, wrapper methods are created. Wicked wizard seems to do a good job, but the names of its methods are counterintuitive sometimes. 

### Back links

In most steps, the back link simply goes to previous step, but not everywhere. Hence, the simple data structure and method were introduced: https://github.com/UKGovernmentBEIS/beis-opss-cosmetics/blob/936a52036539855f707991f18b4550de78288d9f/cosmetics-web/app/controllers/concerns/wizard_concern.rb#L108
This way, back links can be quite simply configured.

2021-11-02 11:38 UTC, slawosz commented on cosmetics-web/app/controllers/responsible_persons/notifications_controller.rb
> +    @responsible_person.notifications
Temporary filtering

2021-11-02 11:38 UTC, slawosz commented on cosmetics-web/app/controllers/responsible_persons/wizard/component_build_controller.rb
>  class ResponsiblePersons::Wizard::ComponentBuildController < SubmitApplicationController
Not longer used in new flow.

2021-11-02 11:43 UTC, slawosz commented on cosmetics-web/app/controllers/responsible_persons/wizard/notification_component_controller.rb
> +        render step
Should be `rerender_current_step`

2021-11-02 11:44 UTC, slawosz commented on cosmetics-web/app/controllers/responsible_persons/wizard/notification_component_controller.rb
> +  def new
Refactor for better understanding

2021-11-02 11:56 UTC, slawosz commented on cosmetics-web/app/controllers/responsible_persons/wizard/notification_product_controller.rb
> +  def update_single_or_multi_component_step
You can try to refactor this.

2022-03-10 09:21 UTC, slawosz commented on cosmetics-web/app/controllers/responsible_persons/notifications_controller.rb
> +      .where.not(state: %i[notification_complete])
Add not `empty` state.

2022-03-30 11:07 UTC, scruti commented on cosmetics-web/app/models/notification.rb
> +
:scissors:?
This does not seem to be used anywhere and we're instead using an alternative implementation (`RoutingQuestionCacheConcern#save_routing_answer`).

2022-04-01 14:17 UTC, slawosz commented on cosmetics-web/app/controllers/responsible_persons/wizard/notification_nanomaterial_controller.rb
> +    non_standard_nanomaterial_notified: %i[confirm_usage select_purposes],
Consider inline proc or lambda

2022-04-01 14:58 UTC, slawosz commented on cosmetics-web/app/models/concerns/notification_state_concern.rb
> +    COMPONENTS_COMPLETE => [READY_FOR_COMPONENTS],
It reads: Disable overriding to value state when we are setting one of the key state.

2022-04-04 10:37 UTC, scruti commented on cosmetics-web/app/controllers/concerns/wizard_concern.rb
> +    render_wizard model
```suggestion
    (steps_to_skip + 1).times do
      step = next_step(step)
    end
    jump_to_step(step)
```

2022-04-04 10:46 UTC, scruti commented on cosmetics-web/app/controllers/concerns/wizard_concern.rb
> +    # If you want your controller to allow different after_eu steps, override this
Before/After EU is not a thing anymore.
```suggestion
```

2022-04-04 10:52 UTC, scruti commented on cosmetics-web/app/controllers/concerns/wizard_concern.rb
> +    @component_name = @component.notification.is_multicomponent? ? @component.name : "the product"
```suggestion
    return redirect_to responsible_person_notification_path(@notification.responsible_person, @notification) if @notification&.notification_complete?

    authorize @notification, :update?, policy_class: ResponsiblePersonNotificationPolicy
    @component_name = @notification.is_multicomponent? ? @component.name : "the product"
```

2022-04-04 11:08 UTC, scruti commented on cosmetics-web/app/controllers/responsible_persons/delete_formulation_file_controller.rb
> +  before_action :set_notification, :set_component
Seems `#set_notification` is redundant in this controller, given that `#set_component` overrides the notification instance var set and authorisation.
```suggestion
  before_action :set_component
```

2022-04-04 11:12 UTC, scruti commented on cosmetics-web/app/controllers/responsible_persons/delete_formulation_file_controller.rb
> +    @component_name = @component.notification.is_multicomponent? ? @component.name : "the product"
```suggestion
    return redirect_to responsible_person_notification_path(@notification.responsible_person, @notification) if @notification&.notification_complete?

    authorize @notification, :update?, policy_class: ResponsiblePersonNotificationPolicy
    @component_name = @notification.is_multicomponent? ? @component.name : "the product"
```

2022-04-04 11:37 UTC, scruti commented on cosmetics-web/app/controllers/responsible_persons/wizard/notification_component_controller.rb
> +    select_special_applicator_type: :contains_special_applicator, # only if contains special applicato: :,
```suggestion
    select_special_applicator_type: :contains_special_applicator, # only if contains special applicator,
```

2022-04-04 11:37 UTC, scruti commented on cosmetics-web/app/controllers/responsible_persons/wizard/notification_component_controller.rb
> +    upload_formulation: :select_formulation_type, # only for range and exac: :,
```suggestion
    upload_formulation: :select_formulation_type, # only for range and exact,
```

2022-04-04 11:40 UTC, scruti commented on cosmetics-web/app/controllers/responsible_persons/wizard/notification_component_controller.rb
> +    upload_poisonus_ingredients: :contains_poisonous_ingredients, # only for frame formulatio: :,
```suggestion
    select_special_applicator_type: :contains_special_applicator, # only if contains special applicator,
    contains_cmrs: :contains_special_applicator,
    add_cmrs: :contains_cmrs,
    select_root_category: :contains_cmrs,
    select_sub_category: :select_root_category,
    select_sub_sub_category: :select_sub_category,
    select_formulation_type: :select_sub_sub_category,
    upload_formulation: :select_formulation_type, # only for range and exact,
    select_frame_formulation: :select_formulation_type, # only for frame formulation,
    contains_poisonous_ingredients: :select_formulation_type, # only for frame formulation,
    upload_poisonus_ingredients: :contains_poisonous_ingredients, # only for frame formulation,
```

2022-04-04 11:46 UTC, scruti commented on cosmetics-web/app/controllers/responsible_persons/wizard/notification_component_controller.rb
> +        render step
```suggestion
        rerender_current_step
```

2022-04-04 11:47 UTC, scruti commented on cosmetics-web/app/controllers/responsible_persons/wizard/notification_component_controller.rb
> +      render step
```suggestion
      rerender_current_step
```

2022-04-04 11:47 UTC, scruti commented on cosmetics-web/app/controllers/responsible_persons/wizard/notification_component_controller.rb
> +      render step
```suggestion
      rerender_current_step
```

2022-04-04 11:48 UTC, scruti commented on cosmetics-web/app/controllers/responsible_persons/wizard/notification_component_controller.rb
> +      render step
```suggestion
      render_next_step @component
    else
      rerender_current_step
```

2022-04-04 11:48 UTC, scruti commented on cosmetics-web/app/controllers/responsible_persons/wizard/notification_component_controller.rb
> +        render_wizard @component
```suggestion
        render_next_step @component
```

2022-04-04 11:49 UTC, scruti commented on cosmetics-web/app/controllers/responsible_persons/wizard/notification_component_controller.rb
> +        render step
```suggestion
        render_next_step @component
      else
        create_required_shades
        rerender_current_step
```

2022-04-04 11:51 UTC, scruti commented on cosmetics-web/app/controllers/responsible_persons/wizard/notification_component_controller.rb
> +      render step
```suggestion
      render_next_step @component
    else
      create_required_cmrs
      rerender_current_step
```

2022-04-04 11:52 UTC, scruti commented on cosmetics-web/app/controllers/responsible_persons/wizard/notification_component_controller.rb
> +        # redirect_to responsible_person_notification_component_build_path(@component.notification.responsible_person, @component.notification, @component, category: sub_category)
:scissors: 
```suggestion
```

2022-04-04 11:53 UTC, scruti commented on cosmetics-web/app/controllers/responsible_persons/wizard/notification_component_controller.rb
> +        render_wizard @component
```suggestion
        render_next_step @component
```

2022-04-04 11:54 UTC, scruti commented on cosmetics-web/app/controllers/responsible_persons/wizard/notification_component_controller.rb
> +      return render step
```suggestion
      return rerender_current_step
```

2022-04-04 11:56 UTC, scruti commented on cosmetics-web/app/controllers/responsible_persons/wizard/notification_component_controller.rb
> +      @component.update(frame_formulation: nil) unless @component.frame_formulation.nil?
```suggestion
    elsif @component.frame_formulation.present?
      @component.update(frame_formulation: nil)
```

2022-04-04 11:57 UTC, scruti commented on cosmetics-web/app/controllers/responsible_persons/wizard/notification_component_controller.rb
> +    render_wizard @component
```suggestion
    render_next_step @component
```

2022-04-04 12:01 UTC, scruti commented on cosmetics-web/spec/support/helpers/wizard.rb
> +      # expect(page).to have_summary_item(key: "pH", value: kit_item[:ph])
:scissors: 
```suggestion
```

2022-04-04 12:09 UTC, scruti commented on cosmetics-web/spec/requests/product_images/delete_product_image_spec.rb
>        it "redirects the user to the edit product images page" do
```suggestion
      it "redirects the user to the notification draft page" do
```

2022-04-04 12:31 UTC, scruti commented on cosmetics-web/spec/models/component_nano_material_spec.rb
> +  pending "add some examples to (or delete) #{__FILE__}"
Should we delete this file? Or add a couple of specs?

2022-04-04 13:14 UTC, scruti commented on cosmetics-web/spec/features/submit_notifications_spec.rb
> +  xscenario "Manual, exact ingredients, single item, with CMRS, no nanomaterials" do
Seems we commented on all the scenarios. Should we delete the file?

2022-04-04 13:40 UTC, scruti commented on cosmetics-web/spec/controllers/responsible_persons/notifications_controller_spec.rb
>      it "redirects to the notification build controller" do
```suggestion
    it "displays the new notification page" do
```

2022-04-04 13:44 UTC, scruti commented on cosmetics-web/lib/tasks/one_off.rake
> +end
:scissors:? Or is it a placeholder that will be completed before merging?

2022-04-04 13:57 UTC, scruti commented on cosmetics-web/app/views/responsible_persons/wizard/notification_component/select_ph_option.html.erb
> +
```suggestion
```

2022-04-04 13:58 UTC, scruti commented on cosmetics-web/app/views/responsible_persons/wizard/notification_component/number_of_shades.html.erb
> +
```suggestion
```

2022-04-04 14:16 UTC, scruti commented on cosmetics-web/app/views/responsible_persons/notifications/edit.html.erb
> +  </div>
Are we listing the error summary twice? Seems this block is re-defining the error summary and tweaking it for this particular page.
But then we're calling `govukErrorSummary` method in [line 35](https://github.com/UKGovernmentBEIS/beis-opss-cosmetics/pull/2277/files#diff-ab57013cd9809ef1d57f83a13356741f6c061d415d1556d707f4812e8361fe4fR35).

Do we want to show both sections?

2022-04-04 14:22 UTC, scruti commented on cosmetics-web/app/views/responsible_persons/drafts/_product_info.html.erb
> +            </p-->
:scissors:  the commented code?
```suggestion
```

2022-04-04 14:23 UTC, scruti commented on cosmetics-web/app/views/responsible_persons/drafts/_product_info.html.erb
> +                </p-->
:scissors:  the commented code?
```suggestion
```

2022-04-04 15:08 UTC, scruti commented on cosmetics-web/app/models/nano_element.rb
> +  # TODO: add uniquenes notification across notifications
If I infer correctly the intention of the comment:
```suggestion
  # TODO: add uniquenes validation across notifications
```

2022-04-04 15:24 UTC, slorek commented on cosmetics-web/app/models/concerns/notification_state_concern.rb
> +      update_state("ready_for_components")
```suggestion
      update_state(READY_FOR_NANOMATERIALS)
    elsif multi_component?
      update_state(DETAILS_COMPLETE)
    else
      update_state(READY_FOR_COMPONENTS)
```

2022-04-04 15:24 UTC, slorek commented on cosmetics-web/app/models/concerns/notification_state_concern.rb
> +      update_state("components_complete")
```suggestion
      update_state(COMPONENTS_COMPLETE)
```

2022-04-04 15:29 UTC, slorek commented on cosmetics-web/app/controllers/responsible_persons/wizard/notification_nanomaterial_controller.rb
> +    non_standard_nanomaterial_notified: %i[confirm_usage select_purposes],
```suggestion
    non_standard_nanomaterial_notified: ->{ @nano_element.multi_purpose? || !@nano_element.multi_purpose? },
```

2022-04-04 15:29 UTC, slorek commented on cosmetics-web/app/controllers/responsible_persons/wizard/notification_nanomaterial_controller.rb
> +  }.freeze
```suggestion
```

2022-04-04 18:25 UTC, scruti commented on cosmetics-web/app/models/concerns/notification_state_concern.rb
> +  end
Instead of commenting suggestions, I opened a PR that is easier to follow altogether: https://github.com/UKGovernmentBEIS/beis-opss-cosmetics/pull/2447

2022-04-04 20:51 UTC, scruti commented on cosmetics-web/config/database.yml
> +    statement_timeout: <%= ENV["STATEMENT_TIMEOUT"] || "15000ms" %>
:raising_hand_man: is this intended to reach production?

2022-04-05 10:18 UTC, scruti commented on cosmetics-web/app/controllers/responsible_persons/wizard/notification_component_controller.rb
> +    render_wizard @component
```suggestion
    render_next_step @component
```

2022-04-05 10:19 UTC, scruti commented on cosmetics-web/app/controllers/responsible_persons/wizard/notification_component_controller.rb
> +        render step
```suggestion
        rerender_current_step
```

2022-04-05 10:20 UTC, scruti commented on cosmetics-web/app/controllers/responsible_persons/wizard/notification_component_controller.rb
> +        render step
```suggestion
        rerender_current_step
```

2022-04-05 10:20 UTC, scruti commented on cosmetics-web/app/controllers/responsible_persons/wizard/notification_component_controller.rb
> +      render step
```suggestion
      rerender_current_step
```

2022-04-05 10:32 UTC, scruti commented on cosmetics-web/app/controllers/responsible_persons/wizard/notification_component_controller.rb
> +      render_next_step @component
```suggestion
      jump_to_step :add_physical_form
```

2022-04-05 10:34 UTC, scruti commented on cosmetics-web/app/controllers/responsible_persons/wizard/notification_component_controller.rb
> +      render_next_step @component
```suggestion
      jump_to_step :contains_poisonous_ingredients
```

2022-04-05 10:37 UTC, scruti commented on cosmetics-web/app/controllers/responsible_persons/wizard/notification_component_controller.rb
> +          render_next_step @component
```suggestion
          jump_to_step :select_ph_option
```

2022-04-05 10:39 UTC, scruti commented on cosmetics-web/app/controllers/responsible_persons/wizard/notification_component_controller.rb
> +      render_next_step @component
```suggestion
      jump_to_step :completed
```

2022-04-05 10:43 UTC, scruti commented on cosmetics-web/app/controllers/responsible_persons/wizard/notification_component_controller.rb
> +        return render_next_step @component
```suggestion
        return  jump_to_step(:select_ph_option)
```

2022-04-05 10:46 UTC, scruti commented on cosmetics-web/app/controllers/responsible_persons/wizard/notification_nanomaterial_controller.rb
> +      render_wizard @nano_element
```suggestion
      render_next_step @nano_element
```

2022-04-05 10:47 UTC, scruti commented on cosmetics-web/app/controllers/responsible_persons/wizard/notification_nanomaterial_controller.rb
> +      render step
```suggestion
      rerender_current_step
```

2022-04-05 10:49 UTC, scruti commented on cosmetics-web/app/controllers/responsible_persons/wizard/notification_nanomaterial_controller.rb
> +      render step
```suggestion
      rerender_current_step
```

2022-04-05 10:50 UTC, scruti commented on cosmetics-web/app/controllers/responsible_persons/wizard/notification_nanomaterial_controller.rb
> +      render_next_step @nano_element
```suggestion
      jump_to_step :must_conform_to_restrictions
```

2022-04-05 10:53 UTC, scruti commented on cosmetics-web/app/controllers/responsible_persons/wizard/notification_nanomaterial_controller.rb
> +      rerender_current_path
:raising_hand_man: This method is not defined anywhere as far as I know
```suggestion
      rerender_current_step
```

2022-04-05 11:18 UTC, scruti commented on cosmetics-web/app/controllers/responsible_persons/wizard/notification_product_controller.rb
> +    end
```suggestion
    case params.dig(:notification, :add_internal_reference)
    when "yes"
      model.save_routing_answer(step, "yes")
      if @notification.update_with_context(notification_params, step)
        render_next_step @notification
      else
        rerender_current_step
      end
    when "no"
      model.save_routing_answer(step, "no")
      @notification.industry_reference = nil
      render_next_step @notification
    else
      @notification.errors.add :add_internal_reference, "Select yes to add an internal reference"
      rerender_current_step
    end
```

2022-04-05 11:24 UTC, scruti commented on cosmetics-web/app/forms/notification_wizard/delete_component_form.rb
> +      raise ActiveRecord::RecordNotFound if %w[notification_complete deleted].include?(notification.state)
Suggestion: replace hardcoded states for constants or the state helper methods:
```suggestion
      raise ActiveRecord::RecordNotFound if notification.notification_completed? || notification.deleted?
```

2022-04-05 11:25 UTC, scruti commented on cosmetics-web/app/forms/notification_wizard/delete_component_form.rb
> +      component.destroy
```suggestion
      notification.components.find(component_id).destroy
```

2022-04-05 11:33 UTC, scruti commented on cosmetics-web/app/forms/notification_wizard/delete_nano_material_form.rb
> +        if value.blank? || value.reject(&:blank?).blank?
Suggestion: Given that for `Array` both `#blank?` and `#empty?` are equivalent, I find using `#empty?` over the "Array" object , while keeping `#blank?` for the contained elements clearer to read in this context:
```suggestion
        if value.empty? || value.reject(&:blank?).empty?
```

2022-04-05 11:36 UTC, scruti commented on cosmetics-web/app/helpers/draft_helper.rb
> +
```suggestion
```

2022-04-05 13:49 UTC, scruti commented on cosmetics-web/app/helpers/draft_helper.rb
> +    # return cannot_start_yet_badge unless component
:scissors: ?

2022-04-05 13:55 UTC, scruti commented on cosmetics-web/app/forms/notification_wizard/delete_nano_material_form.rb
> +      raise ActiveRecord::RecordNotFound if %w[notification_complete deleted].include?(notification.state)
Suggestion: replace hardcoded states for constants or the state helper methods:
```suggestion
      raise ActiveRecord::RecordNotFound if notification.notification_complete? || notification.deleted?
```

2022-04-05 14:13 UTC, scruti commented on cosmetics-web/app/helpers/draft_helper.rb
> +  end
```suggestion
  def total_sections_count
    count = 3
    count += 1 if @notification.nano_materials.present?
    count += 1 if @notification.multi_component?
    count
  end
```

2022-04-05 14:24 UTC, scruti commented on cosmetics-web/app/helpers/responsible_persons/wizard/preselection_helper.rb
> +      @notification.industry_reference.present?
Suggetion: `dig` may be helpful here.
```suggestion
    params.dig(:notification, :add_internal_reference) == "yes" || @notification.industry_reference.present?
```

2022-04-05 14:25 UTC, scruti commented on cosmetics-web/app/models/component.rb
> +  # has_one :nano_material, dependent: :destroy
:scissors: ?

2022-04-05 14:26 UTC, scruti commented on cosmetics-web/app/models/component.rb
> +  has_many :nano_materials, through: :component_nano_materials # dependent: :nullify
```suggestion
  has_many :nano_materials, through: :component_nano_materials
```

2022-04-05 14:27 UTC, scruti commented on cosmetics-web/app/models/component.rb
> +
```suggestion
  has_many :nano_materials, through: :component_nano_materials
```

2022-04-05 14:27 UTC, scruti commented on cosmetics-web/app/models/component.rb
> +  # has_one :nano_material, dependent: :destroy
```suggestion
```

2022-04-05 14:33 UTC, scruti commented on cosmetics-web/app/models/component.rb
> +    save!
Can be reduced to
```suggestion
    return unless save(context: :select_formulation_type)
```

2022-04-05 14:36 UTC, scruti commented on cosmetics-web/app/models/concerns/notification_state_concern.rb
> +    !%w[empty product_name_added].include?(state)
```suggestion
    [EMPTY PRODUCT_NAME_ADDED].exclude?(state)
```

2022-04-05 14:49 UTC, scruti commented on cosmetics-web/app/models/notification.rb
> +    !%w[empty product_name_added].include?(state)
```suggestion
    !empty? && !product_name_added?
```

2022-04-07 15:55 UTC, slawosz commented on cosmetics-web/app/controllers/responsible_persons/wizard/notification_nanomaterial_controller.rb
> +    non_standard_nanomaterial_notified: %i[confirm_usage select_purposes],
I inlined the hash below and changed code a bit, please take a look.

2022-04-08 08:58 UTC, slawosz commented on cosmetics-web/app/controllers/concerns/wizard_concern.rb
> +                      end
I could do it, but without being consistent and using I18n everywhere, here it has very little value.

2022-04-08 09:25 UTC, slawosz commented on cosmetics-web/app/controllers/concerns/wizard_concern.rb
> +  def render_next_step(object)
For some reason it does not work, I don't think its worth digging deeper.

2022-04-08 13:02 UTC, scruti commented on cosmetics-web/config/routes.rb
>            resources :trigger_question, controller: "responsible_persons/wizard/trigger_questions", only: %i[show update new]
Since we are removing the trigger questions controller:
```suggestion
```

2022-04-08 16:31 UTC, scruti approved these changes
Great work @slawosz.
Thanks for going through all the suggestions/requests.

Happy to approve this :clap:

2022-04-12 10:31 UTC, slorek approved these changes

2022-04-12 16:49 UTC, scruti requested changes
Just noticed that one of the latest changes during the code review process introduced a bug in the back-links of the component controller. Will re-approve once fixed!

2022-04-12 16:49 UTC, scruti commented on cosmetics-web/app/controllers/responsible_persons/wizard/notification_component_controller.rb
> +  }.freeze
:raising_hand_man: Please change:
This back routing is broken in its current state. It needs to be inlined in a hash as done with the [nanomaterials controller back routing](https://github.com/UKGovernmentBEIS/beis-opss-cosmetics/pull/2277/files#diff-ecc779a48c164a167806ea97c9e64e08fa27d341ca8c1b9b41e0e75232cb4ec5R28-R31) so the [new version of the previous wizard path calculating method](https://github.com/UKGovernmentBEIS/beis-opss-cosmetics/pull/2277/files#diff-86ee86bc06dbb9137859a989b51b9c2548de1c7c1b4ab6885880391f349cc64cR125-R134) can execute the lambdas.

2022-04-13 12:37 UTC, scruti approved these changes

2022-04-19 18:43 UTC, merged