WIP: Unify ingredient model
UKGovernmentBEIS/beis-opss-cosmetics pull request #2541
Opened 2022-07-15 17:55 UTC by scruti

## Description

## Review apps

https://cosmetics-pr-xxxx-submit-web.london.cloudapps.digital/
https://cosmetics-pr-xxxx-search-web.london.cloudapps.digital/

2022-08-02 09:20 UTC, scruti commented on cosmetics-web/app/controllers/responsible_persons/notifications/components/build_controller.rb
> +      ingredient_number: ingredient_number }
Now `Ingredient` contains `exact_concentration`, `range_concentration` and `poisonous` attributes. So they can be queried without conditional logic. When the value is not set will be returned as `nil` (or `false` for `poisonous`).

2022-08-02 09:22 UTC, scruti commented on cosmetics-web/app/helpers/formula_helper.rb
> -end
Moved to `IngredientHelper`

2022-08-02 09:23 UTC, scruti commented on cosmetics-web/app/helpers/ingredient_helper.rb
> +  end
Moved (and adapted to new `Ingredient` model) from `FormulaHelper`.

2022-08-02 11:13 UTC, scruti commented on cosmetics-web/app/models/component.rb
> +  has_many :ingredients, dependent: :destroy
We keep  `exact_formulas` and `range_formulas`, even when they're not called anymore. To be able to query and debug existing data against the migrated data that will be available as `ingredients`. Once all is good in production, a further PR will be open deleting the `exact_formulas` and `range_formulas` associations and DB tables.

2022-08-02 11:13 UTC, scruti commented on cosmetics-web/app/models/component.rb
> -  end
Moved to`Ingredient` model as scopes.

2022-08-03 12:44 UTC, slorek requested changes

2022-08-03 12:44 UTC, slorek commented on cosmetics-web/app/models/component.rb
> +    ingredients.destroy_all if old_type != notification_type
We may need to keep the destruction of `exact_formulas` and `range_formulas` for now to ensure investigative comparisons (as described in https://github.com/UKGovernmentBEIS/beis-opss-cosmetics/pull/2541/files#r935437128) are accurate.

2022-08-03 12:44 UTC, slorek commented on cosmetics-web/app/models/ingredient.rb
> +    if self.class.where(component_id: component).where("LOWER(inci_name) = ?", inci_name.downcase).any?
Strong suggestion: Rails' `uniqueness` validation takes a `scope` option. We could consider using a `CITEXT` column type for case insensitive comparison. All the other conditionals inside this method can be implemented in a helper method and attached as an option to the built-in `validates` call. Given all these changes this whole method could then potentially be rewritten simply as something like:

`validates :inci_name, uniqueness: { scope: :component_id }, allow_blank: true, if: :notification_present?`

2022-08-03 12:44 UTC, slorek commented on cosmetics-web/app/models/ingredient.rb
> +    if poisonous? && range_concentration.present?
Please change: We have a mixture of conditions inside the validation method but also on the `validate` method call with the `unless` option. Prefer one or the other.

2022-08-03 12:44 UTC, slorek commented on cosmetics-web/app/models/ingredient.rb
> +  def non_poisonous_exact_component_type
Please change: We have a mixture of conditions inside the validation method but also on the `validate` method call with the `unless` option. Prefer one or the other.

2022-08-03 12:44 UTC, slorek commented on cosmetics-web/db/migrate/20220714124143_create_ingredient.rb
> +        t.string "inci_name", null: false
Suggestion: CITEXT type might be advantageous for the uniqueness validation here.

2022-08-03 13:33 UTC, nasirkhanbeis approved these changes
Tested this on the review app with stage data, looking good as expected.

2022-08-03 13:34 UTC, scruti commented on cosmetics-web/app/models/ingredient.rb
> +    return if inci_name_was&.casecmp(inci_name)&.zero? # Do not validate uniqueness if name is unchanged.
The `inci_name_changed?` would be true even if the change is just on the capitalisation. Eg: `Ingredient` into `ingredient`.  

Seeing your comments about the conditionals being in different scopes (will fix that) and CITEX I think we can clean up quite a bit and this line should become unnecessary.

2022-08-03 13:36 UTC, scruti commented on cosmetics-web/app/models/ingredient.rb
> +    if self.class.where(component_id: component).where("LOWER(inci_name) = ?", inci_name.downcase).any?
Very good suggestion :clap: . I have already used `CITEX` for non-case-sensitive email uniqueness validation. Totally forgot about it.

2022-08-04 13:25 UTC, slorek approved these changes

2022-08-04 13:29 UTC, merged